# context
tenantId:     0389929e-887a-4d0a-8d0a-53da10b072cd
clientId:     7b60133e-2ebb-4ef0-ae89-0a876b2cf769
clientSecret:
  keyVault: /subscriptions/ca1e4592-6211-4c03-aac5-e681c1d1ea0d/resourceGroups/platform-keyvaults/providers/Microsoft.KeyVault/vaults/navUtvPlatformVault-001
  secret: a-secret

# application
startMngGrp:  e66a3cea-955c-45e8-b388-e962aa80c514  # guid of the start management group
scopeFilter: managementGroup                        # managementGroup | subscription
scopeDisplayNameFilter: .*                          # reg.ex filter on displayName
assignmentFilter:                                   # optional
  values:
    - nav-policy-1
    - nav-policy-2
  type: include                                     # include | exclude

# technical
httpTimeout: 5                                      # http call timeout in seconds